
import HeroSection from "./components/HeroSection";
import About from "./components/About";
import Team from "./components/Team";
import Faculty from "./components/Faculty";

export const metadata = {
  title: "ARHAM - GGSIPU EDC",
  description: "Generated by create next app",
};

export default function Home() {
  

  return (
    <>
    <HeroSection/>
    <About/>
    <Faculty/>
    <Team/>

    </>
  );
}
